// Copyright 2025 Jascha Wanger / Tarnover, LLC
// SPDX-License-Identifier: Apache-2.0
//
// Cross-language compatibility tests.
//
// Loads the JSON fixtures generated by `scripts/generate_test_vectors.py`
// and asserts that this TypeScript port produces byte-for-byte
// identical canonical bytes, hashes, and signatures. If the Python,
// Rust, and TS implementations disagree, these tests catch it before
// any pin signed by one is rejected by another.

import { describe, it } from 'node:test';
import { strict as assert } from 'node:assert';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

import {
  b64UrlDecodeNoPad,
  b64UrlEncodeNoPad,
  canonicalizeHeader,
  pinFromJSON,
  pinToJSON,
} from '../src/attestation.js';
import { hashText, hashVector, type VecDtype } from '../src/hash.js';
import { Signer } from '../src/signer.js';
import { Verifier } from '../src/verifier.js';

const HERE = dirname(fileURLToPath(import.meta.url));
const TESTVECTORS_DIR = join(HERE, '..', '..', 'testvectors');

interface FixtureBundle {
  public_key_b64: string;
  private_seed_b64: string;
  key_id: string;
  fixtures: Fixture[];
}

interface Fixture {
  name: string;
  input: {
    source: string;
    model: string;
    vector_b64: string;
    vec_dtype: VecDtype;
    vec_dim: number;
    timestamp: string;
  };
  expected: {
    pin_json: string;
    canonical_header_b64: string;
    vec_hash: string;
    source_hash: string;
  };
}

interface NegativeFixture {
  name: string;
  pin_json: string;
  tampered_vector_b64: string;
  expected_error: string;
}

function loadBundle(): FixtureBundle {
  const raw = readFileSync(join(TESTVECTORS_DIR, 'v1.json'), 'utf8');
  return JSON.parse(raw) as FixtureBundle;
}

function loadNegative(): NegativeFixture {
  const raw = readFileSync(join(TESTVECTORS_DIR, 'negative_v1.json'), 'utf8');
  return JSON.parse(raw) as NegativeFixture;
}

function parseVecF32(bytes: Uint8Array, dim: number): Float32Array {
  assert.equal(bytes.length, dim * 4, 'f32 fixture length sanity check');
  // The fixture bytes are already little-endian, which is what Float32Array
  // expects on every realistic Node host (x86_64, arm64). We copy through
  // a DataView to be explicit and platform-safe.
  const out = new Float32Array(dim);
  const view = new DataView(bytes.buffer, bytes.byteOffset, bytes.byteLength);
  for (let i = 0; i < dim; i++) {
    out[i] = view.getFloat32(i * 4, /* littleEndian */ true);
  }
  return out;
}

function parseVecF64(bytes: Uint8Array, dim: number): Float64Array {
  assert.equal(bytes.length, dim * 8, 'f64 fixture length sanity check');
  const out = new Float64Array(dim);
  const view = new DataView(bytes.buffer, bytes.byteOffset, bytes.byteLength);
  for (let i = 0; i < dim; i++) {
    out[i] = view.getFloat64(i * 8, /* littleEndian */ true);
  }
  return out;
}

describe('cross-language positive fixtures (testvectors/v1.json)', () => {
  const bundle = loadBundle();
  assert.ok(bundle.fixtures.length > 0, 'no fixtures to test');

  for (const fx of bundle.fixtures) {
    it(`fixture: ${fx.name}`, () => {
      const dtype = fx.input.vec_dtype;
      const rawBytes = b64UrlDecodeNoPad(fx.input.vector_b64);
      const vector =
        dtype === 'f32'
          ? parseVecF32(rawBytes, fx.input.vec_dim)
          : parseVecF64(rawBytes, fx.input.vec_dim);

      // 1. Component hashes line up with what Python recorded.
      assert.equal(hashText(fx.input.source), fx.expected.source_hash, 'source_hash');
      assert.equal(hashVector(vector, dtype), fx.expected.vec_hash, 'vec_hash');

      // 2. Reproduce the pin from the deterministic seed and confirm
      //    the canonical bytes + signed JSON match Python's output
      //    byte-for-byte.
      const seed = b64UrlDecodeNoPad(bundle.private_seed_b64);
      const signer = Signer.fromPrivateBytes(seed, bundle.key_id);
      const pubExpected = b64UrlDecodeNoPad(bundle.public_key_b64);
      assert.deepEqual(
        Array.from(signer.publicKeyBytes()),
        Array.from(pubExpected),
        'public key derivation',
      );

      const pin = signer.pin({
        source: fx.input.source,
        model: fx.input.model,
        vector,
        vecDtype: dtype,
        timestamp: fx.input.timestamp,
      });

      const canonicalActual = canonicalizeHeader(pin.header);
      const canonicalExpected = b64UrlDecodeNoPad(fx.expected.canonical_header_b64);
      assert.equal(
        b64UrlEncodeNoPad(canonicalActual),
        b64UrlEncodeNoPad(canonicalExpected),
        'canonical header bytes',
      );

      const producedJson = pinToJSON(pin);
      assert.equal(producedJson, fx.expected.pin_json, 'pin JSON byte-for-byte');

      // 3. Round-trip through fromJSON, verify the parsed pin.
      const parsed = pinFromJSON(producedJson);
      const verifier = new Verifier({ [bundle.key_id]: pubExpected });
      const r1 = verifier.verify(parsed, { source: fx.input.source });
      assert.equal(r1.ok, true, `parsed pin verify: ${r1.error} ${r1.detail}`);

      // 4. Verify the JSON Python emitted directly.
      const pythonPin = pinFromJSON(fx.expected.pin_json);
      const r2 = verifier.verify(pythonPin, { source: fx.input.source });
      assert.equal(r2.ok, true, `python pin verify: ${r2.error} ${r2.detail}`);
    });
  }
});

describe('cross-language negative fixture (testvectors/negative_v1.json)', () => {
  it('rejects pin against tampered vector with vector_tampered', () => {
    const neg = loadNegative();
    assert.equal(neg.expected_error, 'vector_tampered');

    const pin = pinFromJSON(neg.pin_json);
    const tampered = parseVecF32(b64UrlDecodeNoPad(neg.tampered_vector_b64), pin.header.vec_dim);

    const bundle = loadBundle();
    const verifier = new Verifier({ [bundle.key_id]: b64UrlDecodeNoPad(bundle.public_key_b64) });
    const result = verifier.verify(pin, { vector: tampered });
    assert.equal(result.ok, false);
    assert.equal(result.error, 'vector_tampered');
  });
});
